version: '3.8'

services:
  mysql-db:
    image: mysql:lts
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ward_management_system
      MYSQL_USER: group17
      MYSQL_PASSWORD: group17@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/ward_management_system
      SPRING_DATASOURCE_USERNAME: group17
      SPRING_DATASOURCE_PASSWORD: group17@123

volumes:
  mysql-data:
